apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world
  namespace: flux-magic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-hello-world
  template:
    metadata:
      labels:
        app: python-hello-world
    spec:
      containers:
      - name: python-app
        image: python:3.9-slim
        command: ["python", "-m", "http.server", "8000"]
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-hello-service
  namespace: flux-magic
spec:
  selector:
    app: python-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
